eyewear/complaints/urls.py
from django.urls import path
from .views import upload_file, file_list

urlpatterns = [
    path('upload/', upload_file, name='upload_file'),
    path('file_list', file_list, name='file_list'),
]

eyewear/eyewear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('',include('orders.urls')),
    path('',include('cart.urls')),
    path('',include('user_address.urls')),
    path('complaints/',include('complaints.urls'))

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

eyewear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

eyewear/complaints/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to="comp")
    order_id=models.CharField(max_length=255)
    uploaded_at = models.DateTimeField(auto_now_add=True)

eyewear/complaints/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document','order_id',)

eyewear/complaints/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import DocumentForm
from .models import Document
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from rest_framework.decorators import api_view
from django.views.decorators.csrf import csrf_exempt

def upload_file(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            print("Form is valid")
            
            document_instance=form.save()
            order_id=document_instance.order_id
            # username=request.session.get('username')
            # print(username)
            # user=User.objects.get(username=username)
            # user_email=user.email
            test_mail="sajagaga2806@gmail.com"
            reciever_mail=[test_mail]
            context={
                "username":"Sample User",
                "order_id":order_id
            }
            mail=render_to_string('complaint_mail.html',context)
            subject=f"Your Complaint for order id:{order_id} is recieved by us"
            new_mail=EmailMessage(subject,mail,"agrawalsiddhi836@gmail.com",reciever_mail)
            new_mail.content_subtype = 'html'
            new_mail.send()
            return redirect('file_list')
        else:
            print("Form is not valid")
    else:
        form = DocumentForm()
    return render(request, 'complaint.html', {'form': form})

def file_list(request):
    if request.method=='POST':
     order_id=request.data.get('order_id')
     documents = Document.objects.filter(order_id=order_id)
     return render(request, 'file_list.html', {'documents': documents})

eyewear/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    
    {% endblock %}
</body>
</html>

eyewear/templates/complaint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Upload File</h1>
    <form method="post" action="{% url 'upload_file' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- <p>
            <label for="id_description">Description:</label>
            {{ form.description }}
        </p>
        <p>
            <label for="id_document">Select a file:</label>
            {{ form.document }}
        </p> -->
        {{ form.as_p }}
        <button type="submit">Upload</button>
    
    </form>
    <a href="{% url 'file_list' %}">View Uploaded Files</a>
</body>
</html>

eyewear/templates/complaint_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>
        Dear{{user_name}}, We have recieved your complaint for the order no {{order_id}}. Our team is working towards resolving your issues.
    </h3>
</body>
</html>

eyewear/templates/file_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Uploaded Files</title>
</head>
<body>
    <h1>Uploaded Files</h1>
    <ul>
        {% for document in documents %}
        <li><a href="{{ document.document.url }}">{{ document.description }}</a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'upload_file' %}">Upload another file</a>
</body>
</html>

eyewear/templates/order_placed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style="height:300px;width:500px;border: 2px solid black">
        <p style="font-weight:500;">
           Dear {{user_name}},
           Thanks for placing order with us. Your order id is {{order_id}}
        </p>
    </div>
    <br>
    <div>
      {% for products in product_name %}
        <p style="font-weight:500;">
          {{products}}
        </p>
        <br>
       {% endfor %} 

       <h3>
        Your order status is:{{status}}
       </h3>
    </div>
</body>
</html>

eyewear/templates/order_status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Dear{{user_name}}, Your order with order id {{order_id}} is {{}}</h3>
</body>
</html>

eyewear/templates/otp_verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Otp Verification</title>
</head>
<body>
    <h3>
        Hi there, your otp for verification is  {{otp}}
    </h3>
    <br>
    <a href="%url 'verify_otp' ">Verify The Otp</a>
</body>
</html>